import re, pathlib
p = pathlib.Path("/Users/jeonghwakim/codex_quant_clean/state/bybit.env")
c = p.read_text()
n = ("SYMBOLS_CSV=BTC/USDT:USDT,ETH/USDT:USDT,SOL/USDT:USDT,XRP/USDT:USDT,"
     "HYPE/USDT:USDT,DOGE/USDT:USDT,ADA/USDT:USDT,XAUT/USDT:USDT,1000PEPE/USDT:USDT,"
     "BNB/USDT:USDT,SUI/USDT:USDT,LINK/USDT:USDT,ZEC/USDT:USDT,LTC/USDT:USDT,"
     "FARTCOIN/USDT:USDT,AAVE/USDT:USDT,RIVER/USDT:USDT,AVAX/USDT:USDT,SKR/USDT:USDT,"
     "DOT/USDT:USDT,WIF/USDT:USDT,ENA/USDT:USDT,BCH/USDT:USDT,ASTER/USDT:USDT,"
     "NEAR/USDT:USDT,PAXG/USDT:USDT,ARB/USDT:USDT,PUMPFUN/USDT:USDT,UNI/USDT:USDT,"
     "HBAR/USDT:USDT,BERA/USDT:USDT,TRX/USDT:USDT,ONDO/USDT:USDT,FIL/USDT:USDT,"
     "OP/USDT:USDT,APT/USDT:USDT,ATOM/USDT:USDT,RENDER/USDT:USDT,TIA/USDT:USDT,"
     "FET/USDT:USDT,PENGU/USDT:USDT,INJ/USDT:USDT,IMX/USDT:USDT,SEI/USDT:USDT,"
     "MANTA/USDT:USDT,JUP/USDT:USDT,STRK/USDT:USDT,W/USDT:USDT,ORDI/USDT:USDT,"
     "CRV/USDT:USDT")
c = re.sub(r"SYMBOLS_CSV=.*", n, c, count=1)
p.write_text(c)
for line in p.read_text().splitlines():
    if line.startswith("SYMBOLS_CSV="):
        print(f"OK: {len(line.split('=',1)[1].split(','))} symbols")
        break
